# TODO: Move away from helmfile. Migrate fully to Terraform.

repositories:

  - name: bitnami
    url:  https://charts.bitnami.com/bitnami


releases:
  - name: user-svc
    namespace: user
    chart: ../service
    wait: true
    set:
      - name: app.name
        value: user
      - name: image.repository
        value: ghcr.io/helpwave/user-svc
      - name: image.tag
        value: edge
      - name: image.pullPolicy
        value: Always
      - name: service.enabled
        value: true
