// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package property_repo

import (
	"github.com/google/uuid"
)

type Property struct {
	ID          uuid.UUID
	SubjectType int32
	FieldType   int32
	Name        string
	Description string
	IsArchived  bool
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
