// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: property_repo.sql

package property_repo

import (
	"context"

	"github.com/google/uuid"
)

const createProperty = `-- name: CreateProperty :exec
INSERT INTO properties
	(id, subject_type, field_type, name)
VALUES ($1, $2, $3, $4)
`

type CreatePropertyParams struct {
	ID          uuid.UUID
	SubjectType int32
	FieldType   int32
	Name        string
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) error {
	_, err := q.db.Exec(ctx, createProperty,
		arg.ID,
		arg.SubjectType,
		arg.FieldType,
		arg.Name,
	)
	return err
}

const getProperties = `-- name: GetProperties :many
SELECT id, subject_type, field_type, name, description, is_archived, set_id, field_type_data_id FROM properties
`

func (q *Queries) GetProperties(ctx context.Context) ([]Property, error) {
	rows, err := q.db.Query(ctx, getProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Property{}
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.FieldType,
			&i.Name,
			&i.Description,
			&i.IsArchived,
			&i.SetID,
			&i.FieldTypeDataID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
