# Generated by Django 4.2.5 on 2023-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rewards',
            field=models.ManyToManyField(blank=True, null=True, to='impulse.reward'),
        ),
    ]
