---
# this is based on the CRDs deployed in keycloak-operator
# the kc-operator then picks these up and creates the keycloak instance
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-db-secret
  labels:
     {{- include "keycloak.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.dbUsername | quote }}
  password: {{ .Values.dbPassword | quote }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instances }}
  db:
    vendor: {{ .Values.dbVendor | quote | default "postgres" }}
    host: {{ .Values.dbHost | quote }}
    usernameSecret:
      name: {{ include "keycloak.fullname" . }}-db-secret
      key: username
    passwordSecret:
      name: {{ include "keycloak.fullname" . }}-db-secret
      key: password
    port: {{ .Values.dbPort | default 5432 }}
    database: {{ .Values.dbDatabase | quote | default "keycloak" }}
  http:
    httpEnabled: {{ .Values.httpEnabled | default false }}
    httpPort: {{ .Values.httpPort | default 8080 }}
    httpsPort: {{ .Values.httpsPort | default 8443 }}
    tlsSecret: {{ include "keycloak.actualTLSSecret" . }}
  hostname:
    hostname: {{ .Values.hostname | quote }}
    strict: {{ .Values.hostnameStrict | default false }}
    admin: {{ .Values.hostnameAdmin | quote | default "" }}
  ingress:
    enabled: {{ .Values.ingressDefault }}
