// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bed_repo.sql

package bed_repo

import (
	"context"

	"github.com/google/uuid"
)

const getBedAndRoomByBedId = `-- name: GetBedAndRoomByBedId :one
SELECT
	beds.id, beds.room_id, beds.name,
	rooms.id, rooms.name, rooms.ward_id
	FROM beds
	JOIN rooms on beds.room_id = rooms.id
	WHERE beds.id = $1
`

type GetBedAndRoomByBedIdRow struct {
	Bed  Bed
	Room Room
}

func (q *Queries) GetBedAndRoomByBedId(ctx context.Context, id uuid.UUID) (GetBedAndRoomByBedIdRow, error) {
	row := q.db.QueryRow(ctx, getBedAndRoomByBedId, id)
	var i GetBedAndRoomByBedIdRow
	err := row.Scan(
		&i.Bed.ID,
		&i.Bed.RoomID,
		&i.Bed.Name,
		&i.Room.ID,
		&i.Room.Name,
		&i.Room.WardID,
	)
	return i, err
}
