linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    # - contextcheck # TODO
    - copyloopvar
    # - cyclop # TODO
    - decorder
    - dogsled
    # - dupl # TODO
    - dupword
    - durationcheck
    # - err113 # TODO
    - errcheck
    - errchkjson
    - errname
    - errorlint
    # - exhaustive # TODO
    # - exhaustruct # TODO
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
    # - gci # TODO
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    # - gocognit # TODO
    # - goconst # TODO
    - gocritic
    # - gocyclo # TODO
    # - godox # TODO: what does this do?
    - gofmt
    # - gofumpt # TODO: what is this?
    - goheader
    # - goimports # TODO: install in dev container
    # - gomoddirectives # TODO: evaluate
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    # - ireturn # TODO
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    # - nestif # TODO
    - nilerr
    # - nlreturn # TODO
    - noctx
    - nolintlint
    # - paralleltest # TODO
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    # - protogetter # TODO
    - reassign
    # - revive # TODO
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    # - stylecheck # TODO
    - tagalign
    # - tagliatelle # TODO
    - tenv
    - testableexamples
    - testifylint
    # - testpackage # TODO
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

  disable:
    - depguard
    - funlen
    - execinquery
    - gochecknoglobals
    - godot
    - mnd
    - nonamedreturns
    - nilnil
    - nosprintfhostport
    - varnamelen
    - wrapcheck
    - wsl
