linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable-all: true

  disable:
    - contextcheck # too many false-positives
    - depguard # no need
    - ireturn # no need
    - funlen # we tend to have long funlens, who cares?
    - execinquery # deprecated
    - goimports # unused
    - gochecknoglobals # we currently make use of globals
    - godot # petty linter
    - gomnd # deprecated
    - gomoddirectives # not needed
    - gofumpt # false positives
    - mnd # too many false-positives
    - nonamedreturns # we like named returns
    - nilnil # we like (nil, nil) sometimes
    - nosprintfhostport # little benefits
    - varnamelen # we accept this
    - wrapcheck # does not matter to us
    - wsl # too aggressive
    - exportloopref # deprecated
    - tagalign # too many false-positives

    # TODOs: #865
    - cyclop # TODO
    - dupl # TODO
    - exhaustruct # TODO
    - gci # TODO
    - gocognit # TODO
    - gocyclo # TODO
    - godox # TODO
    - nestif # TODO
    - nlreturn # TODO
    - paralleltest # TODO
    - protogetter # TODO
    - revive # TODO
    - testpackage # TODO

linters-settings:
  goconst:
    ignore-tests: true
    min-occurrences: 2
    ignore-strings: '(true|false)' # regex
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
        xml: snake
        toml: snake
        bson: snake
        avro: snake
        mapstructure: snake
        env: upperSnake
        envconfig: upperSnake
      overrides:
        - pkg: user-svc/internal/hwkc
          rules:
            json: camel
