FROM python:3.12.1-alpine

# gRPC Port
EXPOSE 8080
# HTTP Port
EXPOSE 8000

WORKDIR /app
COPY services/impulse_svc/. /app
COPY lib/python/ /lib/python/
COPY docker-run-migrations-impulse-svc.sh ./run-migrations.sh
RUN chmod +x run-migrations.sh

RUN pip install -r requirements.txt

CMD sleep infinity
