FROM python:3.12.1

# gRPC Port
EXPOSE 8080
# HTTP Port
EXPOSE 8000

WORKDIR /app

RUN apt update -y && apt-get install python3-dev -y
RUN mkdir -p /libs/python/

COPY libs/python/ /libs/python/
COPY services/impulse_svc/. /app
COPY docker-run-migrations-impulse-svc.sh ./run-migrations.sh
RUN chmod +x run-migrations.sh

RUN pip install -r requirements.txt

CMD sleep infinity
