apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  nameResolution:
    component: "consul"
    configuration:
      selfRegister: true
      client:
        address: "consul:8500"
    checks:
      - name: "Dapr Health Status"
        checkID: "daprHealth:${APP_ID}"
        interval: "15s"
        http: "http://${HOST_ADDRESS}:${DAPR_HTTP_PORT}/v1.0/healthz"
      - name: "Service Health Status"
        checkID: "serviceHealth:${APP_ID}"
        interval: "15s"
        http: "http://${HOST_ADDRESS}:${APP_PORT}/health"
