version: '3'

services:

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: tech@helpwave.de
      PGADMIN_DEFAULT_PASSWORD: tech@helpwave.de
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
    ports:
      - "5433:80"

  redis:
    image: redis:6
    profiles:
      - full
    restart: unless-stopped

  apisix:
    build:
      context: ..
      dockerfile: Dockerfile.apisix
    profiles:
      - full
    restart: unless-stopped
    volumes:
      - ./dapr.yaml:/usr/local/apisix/dapr/config.yaml:ro
      - ../apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro # for hot-reloading
    ports:
      - "9080:9080"

  task-svc:
    build:
      context: ..
      dockerfile: Dockerfile.standalone
      args:
        - SERVICE=task-svc
    profiles:
      - full
    volumes:
      - ./dapr.yaml:/app/dapr/dapr.yaml:ro
    restart: unless-stopped
    environment:
      INSECURE_FAKE_TOKEN_ENABLE: true
      POSTGRES_DSN: postgres://postgres:postgres@postgres/task-svc
      SECRETSTORE_REDIS_HOST: "redis:6379"
      SECRETSTORE_REDIS_PASSWORD: ""
      SECRETSTORE_REDIS_USERNAME: ""

  user-svc:
    build:
      context: ..
      dockerfile: Dockerfile.standalone
      args:
        - SERVICE=user-svc
    profiles:
      - full
    volumes:
      - ./dapr.yaml:/app/dapr/dapr.yaml:ro
    restart: unless-stopped
    environment:
      INSECURE_FAKE_TOKEN_ENABLE: true
      POSTGRES_DSN: postgres://postgres:postgres@postgres/user-svc
      SECRETSTORE_REDIS_HOST: "redis:6379"
      SECRETSTORE_REDIS_PASSWORD: ""
      SECRETSTORE_REDIS_USERNAME: ""

  ory-svc:
    build:
      context: ..
      dockerfile: Dockerfile.standalone
      args:
        - SERVICE=ory-svc
        - APP_PROTOCOL=http
    profiles:
      - full
    volumes:
      - ./dapr.yaml:/app/dapr/dapr.yaml:ro
    restart: unless-stopped
    environment:
      SECRETSTORE_REDIS_HOST: "redis:6379"
      SECRETSTORE_REDIS_PASSWORD: ""
      SECRETSTORE_REDIS_USERNAME: ""
