// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: user_repo.sql

package user_repo

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, nickname, name, avatar_url) VALUES ($1, $2, $3, $4, $5) RETURNING id, email, nickname, name, avatar_url
`

type CreateUserParams struct {
	ID        uuid.UUID
	Email     string
	Nickname  string
	Name      string
	AvatarUrl *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Nickname,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const existsUser = `-- name: ExistsUser :one
SELECT EXISTS(
	SELECT 1
	FROM users
	WHERE id = $1
) user_exists
`

func (q *Queries) ExistsUser(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsUser, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, nickname, name, avatar_url FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}
