ALTER TABLE tasks DROP COLUMN IF EXISTS consistency;
ALTER TABLE patients DROP COLUMN IF EXISTS consistency;
ALTER TABLE rooms DROP COLUMN IF EXISTS consistency;
ALTER TABLE beds DROP COLUMN IF EXISTS consistency;
