// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package room_repo

import (
	"github.com/google/uuid"
)

type Bed struct {
	ID             uuid.UUID
	RoomID         uuid.UUID
	OrganizationID uuid.UUID
	Name           string
}

type Room struct {
	ID             uuid.UUID
	Name           string
	OrganizationID uuid.UUID
	WardID         uuid.UUID
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type TaskTemplate struct {
	ID             uuid.UUID
	Name           string
	Description    string
	WardID         uuid.NullUUID
	CreatedBy      uuid.UUID
	OrganizationID uuid.UUID
}

type TaskTemplateSubtask struct {
	ID             uuid.UUID
	TaskTemplateID uuid.UUID
	Name           string
}

type Ward struct {
	ID             uuid.UUID
	Name           string
	OrganizationID uuid.UUID
}
