// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: room_repo.sql

package room_repo

import (
	"context"

	"github.com/google/uuid"
)

const getRoomByBedId = `-- name: GetRoomByBedId :one
SELECT
	rooms.id, rooms.name, rooms.organization_id, rooms.ward_id
	FROM rooms
	LEFT JOIN beds ON beds.room_id = rooms.id
	WHERE (beds.id = $1)
`

func (q *Queries) GetRoomByBedId(ctx context.Context, bedID uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByBedId, bedID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.WardID,
	)
	return i, err
}
