# TODO: Move away from helmfile. Migrate fully to Terraform.

repositories:
  - name: bitnami
    url:  https://charts.bitnami.com/bitnami

releases:
  # TODO: Move away from one PostgreSQL-Server per service.
  - name: keycloak-postgres
    namespace: keycloak
    chart: bitnami/postgresql
    wait: true
    set:
      - name: auth.enablePostgresUser
        value: true
      - name: auth.database
        value: keycloak
      - name: auth.username
        value: helpwave
      # TODO: Use secrets
      - name: auth.postgresPassword
        value: helpwave
      - name: auth.password
        value: helpwave
  - name: keycloak
    namespace: keycloak
    chart: .
    wait: true
    set:
      - name: keycloak-operator.nameOverride
        value: "operator"
      - name: keycloak-operator.keycloakImage.repository
        value: "ghcr.io/helpwave/keycloak"
      - name: keycloak-operator.keycloakImage.tag
        value: "edge"
      - name: hostname
        value: "staging-sso.helpwave.de"
      - name: hostnameStrict
        value: false
      - name: dbHost
        value: "keycloak-postgres-postgresql.keycloak"
      - name: dbPort
        value: 5432
      - name: dbDatabase
        value: "keycloak"
      # TODO: Use secrets
      - name: dbUsername
        value: "helpwave"
      - name: dbPassword
        value: "helpwave"
      - name: httpEnabled
        value: true
      - name: tlsUseFakeCert
        value: true
      - name: ingressCustom
        value: true
      - name: svcAuthSecret
        value: "notReallySecret" # TODO: use vault ("**${vault.**_key_**}**")
      - name: svcAuthCallback
        value: "https://staging-api.helpwave.de/auth-svc/callback" # TODO
      - name: svcUserSecret
        value: "notSecretEither" # TODO: use vault ("**${vault.**_key_**}**")
