# fly.toml app configuration file generated for helpwave-staging-spicedb on 2024-08-20T16:19:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helpwave-staging-jaeger'
primary_region = 'ams'

[build]
image = 'jaegertracing/all-in-one:1.60'

# TODO: healthchecks

[env]
COLLECTOR_OTLP_ENABLED = 'true'

[[vm]]
size = 'shared-cpu-1x'
