# fly.toml app configuration file generated for helpwave-staging-spicedb on 2024-08-20T16:19:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helpwave-staging-spicedb'
primary_region = 'ams'

[build]
  image = 'authzed/spicedb:v1.31.0' # TODO: renovate

[deploy]
  release_command = 'migrate head'

# TODO: healthchecks (figure out how how to use a secret in checks)

[env]
  SPICEDB_DATASTORE_ENGINE = 'postgres'
  SPICEDB_SKIP_RELEASE_CHECK = 'true' # we know due to renovate on dev compose
  SPICEDB_TELEMETRY_ENDPOINT = '' # prevent spicedb from talking home

  # record traces for all requests on staging
  # SPICEDB_OTEL_SAMPLE_RATIO=1
  # Secrets:
  #  SPICEDB_GRPC_PRESHARED_KEY=<string>
  #  SPICEDB_DATASTORE_CONN_URI=postgres://<user>:<password>@<host>:<port>/spicedb?sslmode=disable
  #  SPICEDB_OTEL_ENDPOINT= TODO
  #  SPICEDB_OTEL_INSECURE=
  #  SPICEDB_OTEL_PROVIDER=

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 9090
  path = '/metrics'

[experimental]
  cmd = ["serve"]
