{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 1337
      targetPort: 3500
      protocol: TCP
      name: dapr-public-lel
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}
