# File is copied to /usr/local/apisix/conf/config.yaml in docker image (Dockerfile.apisix)

apisix:
  node_listen:
    - port: 9080
      enable_http2: true

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

#END
