primary_region = "ams"

[build]
  dockerfile = "../../Dockerfile.standalone"

[build.args]
  SERVICE = "ory-svc"
  APP_PROTOCOL = "http"

[env]
  OTEL_DISABLE=true
  METRICS_ADDR=:9091

[deploy]
  strategy = "bluegreen"

[checks]
  [checks.dapr_sidecar]
    grace_period = "15s"
    interval = "10s"
    method = "get"
    path = "/v1.0/healthz"
    port = 3500
    timeout = "2s"
    type = "http"

[metrics]
  port = 9091
  path = "/metrics"
