# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

instances: 1

# publicly available hostname
hostname: ""
hostnameStrict: true
hostnameAdmin: ""

httpEnabled: false
httpPort: 8080
httpsPort: 8443

tlsUseFakeCert: false # if true you can leave tlsSecret empty
tlsSecret: ""

# additionally to the keycloak service provided by the operator
# we need another internal service that maps 443 -> 8443.
# The operator does not allow us to customize its service
# and using the port 443 in the pod would require the root user
internalService:
  enabled: true
  type: ClusterIP
  httpsPort: 443

dbVendor: postgres
dbHost: ""
dbPort: 5432
dbDatabase: "keycloak"

# TODO: let vault manage this
dbUsername: ""
dbPassword: ""

# The deployment is, by default, exposed through a basic ingress.
# it is not compatible with the nginx ingress
ingressDefault: false
ingressCustom: true

svcAuthSecret: "" # TODO: use vault ("**${vault.**_key_**}**")
svcAuthCallback: ""

svcUserSecret: "" # TODO: use vault ("**${vault.**_key_**}**")
