# TODO: Move away from helmfile. Migrate fully to Terraform.

releases:
  - name: auth-svc
    namespace: auth
    chart: ../service
    wait: true
    set:
      - name: app.name
        value: auth
      - name: image.repository
        value: ghcr.io/helpwave/auth-svc
      - name: image.tag
        value: edge
      - name: image.pullPolicy
        value: Always
      - name: service.enabled
        value: true
      - name: postgres.disabled
        value: true
      - name: keycloakClientID
        value: "auth-svc"
      - name: keycloakClientSecret
        value: "notReallySecret" # TODO
      - name: keycloakCallbackURL
        value: "https://not-deployed-yet/callback" # TODO
