// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBed = `-- name: CreateBed :one
INSERT INTO beds (room_id, organization_id, name) VALUES ($1, $2, $3) RETURNING id, room_id, organization_id, name
`

type CreateBedParams struct {
	RoomID         uuid.UUID
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) CreateBed(ctx context.Context, arg CreateBedParams) (Bed, error) {
	row := q.db.QueryRow(ctx, createBed, arg.RoomID, arg.OrganizationID, arg.Name)
	var i Bed
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OrganizationID,
		&i.Name,
	)
	return i, err
}
