DROP TABLE IF EXISTS rooms_have_departments;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS emergency_rooms;
DROP EXTENSION IF EXISTS earthdistance;
DROP EXTENSION IF EXISTS cube;
DROP EXTENSION IF EXISTS "uuid-ossp";
