primary_region = "ams"

[build]
  dockerfile = "../../Dockerfile.impulse-svc"

[build.args]
  SERVICE = "impulse-svc"

[deploy]
  release_command = "sh -c 'sleep 30s && ./run-migrations.sh'" # fly (hopefully) is done with its networking

[processes]
  web = "python manage.py runserver 0.0.0.0:8000"
  grpc = "python manage.py grpcserver --port 8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["grpc"]

  [[services.ports]]
    handlers = ["tls"]
    port = 8080

  [services.ports.tls_options]
    alpn = ["h2"]

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["web"]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
