// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bed is the predicate function for bed builders.
type Bed func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// SubTask is the predicate function for subtask builders.
type SubTask func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskTemplate is the predicate function for tasktemplate builders.
type TaskTemplate func(*sql.Selector)

// TaskTemplateSubTask is the predicate function for tasktemplatesubtask builders.
type TaskTemplateSubTask func(*sql.Selector)

// Ward is the predicate function for ward builders.
type Ward func(*sql.Selector)
