# Generated by Django 4.2.5 on 2023-09-22 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('daily', 'Täglich'), ('quest', 'Mission')], max_length=10)),
                ('category', models.CharField(choices=[('food', 'Ernährung'), ('fitness', 'Fitness'), ('mental', 'Mentale Gesundheit')], max_length=10)),
                ('points', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers')], max_length=10)),
                ('birthday', models.DateTimeField()),
                ('pal', models.FloatField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('done_datetime', models.DateTimeField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grpc_service.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grpc_service.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='challenges',
            field=models.ManyToManyField(through='grpc_service.UserChallenge', to='grpc_service.challenge'),
        ),
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.ManyToManyField(to='grpc_service.reward'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grpc_service.team'),
        ),
    ]
