# Generated by Django 4.2.5 on 2023-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0002_alter_challenge_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='done',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(),
        ),
    ]
