# Generated by Django 4.2.5 on 2023-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0003_alter_user_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', 'Männlich'), ('1', 'Weiblich'), ('2', 'Divers')], max_length=10),
        ),
    ]
