# Generated by Django 4.2.5 on 2023-09-23 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0003_alter_user_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationStr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('type', models.CharField(choices=[('qr', 'QR Code')], max_length=10)),
                ('value', models.CharField(max_length=512)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grpc_service.challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationInt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('type', models.CharField(choices=[('timer', 'Stopuhr'), ('number', 'Nummer')], max_length=10)),
                ('value', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grpc_service.challenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
