# Generated by Django 4.2.5 on 2023-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0003_remove_user_sex_remove_userchallenge_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='done',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
