# Generated by Django 4.2.5 on 2023-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0003_alter_user_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
