# Generated by Django 4.2.5 on 2023-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0004_remove_reward_image_remove_team_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Fitness'), (3, 'Mental')]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Quest')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Diverse')]),
        ),
    ]
