# Generated by Django 4.2.5 on 2023-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0005_alter_challenge_category_alter_challenge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationint',
            name='type',
            field=models.IntegerField(choices=[(1, 'Timer'), (2, 'Number')]),
        ),
        migrations.AlterField(
            model_name='verificationstr',
            name='type',
            field=models.IntegerField(choices=[(1, 'Qr')]),
        ),
    ]
