# Generated by Django 4.2.5 on 2023-09-22 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0005_challenge_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='done',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 18, 3, 11, 72121)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='done_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 18, 3, 20, 20853)),
            preserve_default=False,
        ),
    ]
