# Generated by Django 4.2.5 on 2023-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Männlich'), ('2', 'Weiblich'), ('3', 'Divers')]),
        ),
    ]
