# Generated by Django 4.2.5 on 2023-09-22 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0006_remove_user_age_remove_userchallenge_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.ManyToManyField(to='grpc_service.reward'),
        ),
    ]
