# Generated by Django 4.2.5 on 2023-09-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpc_service', '0007_reward_team_user_image_alter_challenge_end_datetime_and_more'),
        ('grpc_service', '0007_reward_user_rewards'),
    ]

    operations = [
    ]
