{{ if .Values.ingressCustom }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "keycloak.fullname" . }}-route
spec:
  http:
  - name: kc
    match:
    {{ if .Values.hostname }}
      hosts:
      - {{ .Values.hostname }}
    {{ end }}
      paths:
      - /*
    backends:
    - serviceName: keycloak-service
      servicePort: 8443
{{ end }}
