primary_region = "ams"

[build]
  dockerfile = "../../Dockerfile.standalone"

[build.args]
  SERVICE = "tasks-svc"

[env]
  INSECURE_FAKE_TOKEN_ENABLE = true
  OTEL_EXPORTER_OTLP_ENDPOINT = "http://helpwave-staging-jaeger.internal:4317"
  OTEL_EXPORTER_OTLP_INSECURE = true
  METRICS_ADDR = ":9091"

[deploy]
  strategy = "bluegreen"
  release_command = "./run-migrations.sh"

[metrics]
  port = 9091
  path = "/metrics"

[checks]
  [checks.dapr_sidecar]
    grace_period = "15s"
    interval = "10s"
    method = "get"
    path = "/v1.0/healthz"
    port = 3500
    timeout = "2s"
    type = "http"

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
