primary_region = "ams"

[build]
  dockerfile = "../../Dockerfile.standalone"

[build.args]
  SERVICE = "tasks-svc"

[env]
  INSECURE_FAKE_TOKEN_ENABLE=true
  OTEL_DISABLE=true

[deploy]
  strategy = "bluegreen"
  release_command = "sh -c 'sleep 30s && ./run-migrations.sh'" # fly (hopefully) is done with its networking

[checks]
  [checks.dapr_sidecar]
    grace_period = "15s"
    interval = "10s"
    method = "get"
    path = "/v1.0/healthz"
    port = 3500
    timeout = "2s"
    type = "http"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
