// Code generated by ent, DO NOT EDIT.

package ent

import (
	"task-svc/ent/bed"
	"task-svc/ent/patient"
	"task-svc/ent/room"
	"task-svc/ent/schema"
	"task-svc/ent/subtask"
	"task-svc/ent/task"
	"task-svc/ent/tasktemplate"
	"task-svc/ent/tasktemplatesubtask"
	"task-svc/ent/ward"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bedFields := schema.Bed{}.Fields()
	_ = bedFields
	// bedDescID is the schema descriptor for id field.
	bedDescID := bedFields[0].Descriptor()
	// bed.DefaultID holds the default value on creation for the id field.
	bed.DefaultID = bedDescID.Default.(func() uuid.UUID)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescID is the schema descriptor for id field.
	patientDescID := patientFields[0].Descriptor()
	// patient.DefaultID holds the default value on creation for the id field.
	patient.DefaultID = patientDescID.Default.(func() uuid.UUID)
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescID is the schema descriptor for id field.
	roomDescID := roomFields[0].Descriptor()
	// room.DefaultID holds the default value on creation for the id field.
	room.DefaultID = roomDescID.Default.(func() uuid.UUID)
	subtaskFields := schema.SubTask{}.Fields()
	_ = subtaskFields
	// subtaskDescDone is the schema descriptor for done field.
	subtaskDescDone := subtaskFields[2].Descriptor()
	// subtask.DefaultDone holds the default value on creation for the done field.
	subtask.DefaultDone = subtaskDescDone.Default.(bool)
	// subtaskDescID is the schema descriptor for id field.
	subtaskDescID := subtaskFields[0].Descriptor()
	// subtask.DefaultID holds the default value on creation for the id field.
	subtask.DefaultID = subtaskDescID.Default.(func() uuid.UUID)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescDescription is the schema descriptor for description field.
	taskDescDescription := taskFields[2].Descriptor()
	// task.DefaultDescription holds the default value on creation for the description field.
	task.DefaultDescription = taskDescDescription.Default.(string)
	// taskDescPublic is the schema descriptor for public field.
	taskDescPublic := taskFields[3].Descriptor()
	// task.DefaultPublic holds the default value on creation for the public field.
	task.DefaultPublic = taskDescPublic.Default.(bool)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	tasktemplateFields := schema.TaskTemplate{}.Fields()
	_ = tasktemplateFields
	// tasktemplateDescDescription is the schema descriptor for description field.
	tasktemplateDescDescription := tasktemplateFields[2].Descriptor()
	// tasktemplate.DefaultDescription holds the default value on creation for the description field.
	tasktemplate.DefaultDescription = tasktemplateDescDescription.Default.(string)
	// tasktemplateDescID is the schema descriptor for id field.
	tasktemplateDescID := tasktemplateFields[0].Descriptor()
	// tasktemplate.DefaultID holds the default value on creation for the id field.
	tasktemplate.DefaultID = tasktemplateDescID.Default.(func() uuid.UUID)
	tasktemplatesubtaskFields := schema.TaskTemplateSubTask{}.Fields()
	_ = tasktemplatesubtaskFields
	// tasktemplatesubtaskDescID is the schema descriptor for id field.
	tasktemplatesubtaskDescID := tasktemplatesubtaskFields[0].Descriptor()
	// tasktemplatesubtask.DefaultID holds the default value on creation for the id field.
	tasktemplatesubtask.DefaultID = tasktemplatesubtaskDescID.Default.(func() uuid.UUID)
	wardFields := schema.Ward{}.Fields()
	_ = wardFields
	// wardDescID is the schema descriptor for id field.
	wardDescID := wardFields[0].Descriptor()
	// ward.DefaultID holds the default value on creation for the id field.
	ward.DefaultID = wardDescID.Default.(func() uuid.UUID)
}
