// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"task-svc/ent/subtask"
	"task-svc/ent/task"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubTaskCreate is the builder for creating a SubTask entity.
type SubTaskCreate struct {
	config
	mutation *SubTaskMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (stc *SubTaskCreate) SetName(s string) *SubTaskCreate {
	stc.mutation.SetName(s)
	return stc
}

// SetDone sets the "done" field.
func (stc *SubTaskCreate) SetDone(b bool) *SubTaskCreate {
	stc.mutation.SetDone(b)
	return stc
}

// SetNillableDone sets the "done" field if the given value is not nil.
func (stc *SubTaskCreate) SetNillableDone(b *bool) *SubTaskCreate {
	if b != nil {
		stc.SetDone(*b)
	}
	return stc
}

// SetCreatedBy sets the "created_by" field.
func (stc *SubTaskCreate) SetCreatedBy(u uuid.UUID) *SubTaskCreate {
	stc.mutation.SetCreatedBy(u)
	return stc
}

// SetID sets the "id" field.
func (stc *SubTaskCreate) SetID(u uuid.UUID) *SubTaskCreate {
	stc.mutation.SetID(u)
	return stc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (stc *SubTaskCreate) SetNillableID(u *uuid.UUID) *SubTaskCreate {
	if u != nil {
		stc.SetID(*u)
	}
	return stc
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (stc *SubTaskCreate) SetTaskID(id uuid.UUID) *SubTaskCreate {
	stc.mutation.SetTaskID(id)
	return stc
}

// SetTask sets the "task" edge to the Task entity.
func (stc *SubTaskCreate) SetTask(t *Task) *SubTaskCreate {
	return stc.SetTaskID(t.ID)
}

// Mutation returns the SubTaskMutation object of the builder.
func (stc *SubTaskCreate) Mutation() *SubTaskMutation {
	return stc.mutation
}

// Save creates the SubTask in the database.
func (stc *SubTaskCreate) Save(ctx context.Context) (*SubTask, error) {
	stc.defaults()
	return withHooks(ctx, stc.sqlSave, stc.mutation, stc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (stc *SubTaskCreate) SaveX(ctx context.Context) *SubTask {
	v, err := stc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stc *SubTaskCreate) Exec(ctx context.Context) error {
	_, err := stc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stc *SubTaskCreate) ExecX(ctx context.Context) {
	if err := stc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (stc *SubTaskCreate) defaults() {
	if _, ok := stc.mutation.Done(); !ok {
		v := subtask.DefaultDone
		stc.mutation.SetDone(v)
	}
	if _, ok := stc.mutation.ID(); !ok {
		v := subtask.DefaultID()
		stc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stc *SubTaskCreate) check() error {
	if _, ok := stc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubTask.name"`)}
	}
	if _, ok := stc.mutation.Done(); !ok {
		return &ValidationError{Name: "done", err: errors.New(`ent: missing required field "SubTask.done"`)}
	}
	if _, ok := stc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SubTask.created_by"`)}
	}
	if _, ok := stc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "SubTask.task"`)}
	}
	return nil
}

func (stc *SubTaskCreate) sqlSave(ctx context.Context) (*SubTask, error) {
	if err := stc.check(); err != nil {
		return nil, err
	}
	_node, _spec := stc.createSpec()
	if err := sqlgraph.CreateNode(ctx, stc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	stc.mutation.id = &_node.ID
	stc.mutation.done = true
	return _node, nil
}

func (stc *SubTaskCreate) createSpec() (*SubTask, *sqlgraph.CreateSpec) {
	var (
		_node = &SubTask{config: stc.config}
		_spec = sqlgraph.NewCreateSpec(subtask.Table, sqlgraph.NewFieldSpec(subtask.FieldID, field.TypeUUID))
	)
	if id, ok := stc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := stc.mutation.Name(); ok {
		_spec.SetField(subtask.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := stc.mutation.Done(); ok {
		_spec.SetField(subtask.FieldDone, field.TypeBool, value)
		_node.Done = value
	}
	if value, ok := stc.mutation.CreatedBy(); ok {
		_spec.SetField(subtask.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if nodes := stc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtask.TaskTable,
			Columns: []string{subtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_subtasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubTaskCreateBulk is the builder for creating many SubTask entities in bulk.
type SubTaskCreateBulk struct {
	config
	err      error
	builders []*SubTaskCreate
}

// Save creates the SubTask entities in the database.
func (stcb *SubTaskCreateBulk) Save(ctx context.Context) ([]*SubTask, error) {
	if stcb.err != nil {
		return nil, stcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(stcb.builders))
	nodes := make([]*SubTask, len(stcb.builders))
	mutators := make([]Mutator, len(stcb.builders))
	for i := range stcb.builders {
		func(i int, root context.Context) {
			builder := stcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, stcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, stcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, stcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (stcb *SubTaskCreateBulk) SaveX(ctx context.Context) []*SubTask {
	v, err := stcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (stcb *SubTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := stcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stcb *SubTaskCreateBulk) ExecX(ctx context.Context) {
	if err := stcb.Exec(ctx); err != nil {
		panic(err)
	}
}
