// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"task-svc/ent/predicate"
	"task-svc/ent/tasktemplatesubtask"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskTemplateSubTaskDelete is the builder for deleting a TaskTemplateSubTask entity.
type TaskTemplateSubTaskDelete struct {
	config
	hooks    []Hook
	mutation *TaskTemplateSubTaskMutation
}

// Where appends a list predicates to the TaskTemplateSubTaskDelete builder.
func (ttstd *TaskTemplateSubTaskDelete) Where(ps ...predicate.TaskTemplateSubTask) *TaskTemplateSubTaskDelete {
	ttstd.mutation.Where(ps...)
	return ttstd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ttstd *TaskTemplateSubTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ttstd.sqlExec, ttstd.mutation, ttstd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ttstd *TaskTemplateSubTaskDelete) ExecX(ctx context.Context) int {
	n, err := ttstd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ttstd *TaskTemplateSubTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tasktemplatesubtask.Table, sqlgraph.NewFieldSpec(tasktemplatesubtask.FieldID, field.TypeUUID))
	if ps := ttstd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ttstd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ttstd.mutation.done = true
	return affected, err
}

// TaskTemplateSubTaskDeleteOne is the builder for deleting a single TaskTemplateSubTask entity.
type TaskTemplateSubTaskDeleteOne struct {
	ttstd *TaskTemplateSubTaskDelete
}

// Where appends a list predicates to the TaskTemplateSubTaskDelete builder.
func (ttstdo *TaskTemplateSubTaskDeleteOne) Where(ps ...predicate.TaskTemplateSubTask) *TaskTemplateSubTaskDeleteOne {
	ttstdo.ttstd.mutation.Where(ps...)
	return ttstdo
}

// Exec executes the deletion query.
func (ttstdo *TaskTemplateSubTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := ttstdo.ttstd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tasktemplatesubtask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ttstdo *TaskTemplateSubTaskDeleteOne) ExecX(ctx context.Context) {
	if err := ttstdo.Exec(ctx); err != nil {
		panic(err)
	}
}
