// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"task-svc/ent/predicate"
	"task-svc/ent/room"
	"task-svc/ent/tasktemplate"
	"task-svc/ent/ward"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WardQuery is the builder for querying Ward entities.
type WardQuery struct {
	config
	ctx               *QueryContext
	order             []ward.OrderOption
	inters            []Interceptor
	predicates        []predicate.Ward
	withRooms         *RoomQuery
	withTaskTemplates *TaskTemplateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WardQuery builder.
func (wq *WardQuery) Where(ps ...predicate.Ward) *WardQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WardQuery) Limit(limit int) *WardQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WardQuery) Offset(offset int) *WardQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WardQuery) Unique(unique bool) *WardQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WardQuery) Order(o ...ward.OrderOption) *WardQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryRooms chains the current query on the "rooms" edge.
func (wq *WardQuery) QueryRooms() *RoomQuery {
	query := (&RoomClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ward.Table, ward.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ward.RoomsTable, ward.RoomsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTaskTemplates chains the current query on the "task_templates" edge.
func (wq *WardQuery) QueryTaskTemplates() *TaskTemplateQuery {
	query := (&TaskTemplateClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ward.Table, ward.FieldID, selector),
			sqlgraph.To(tasktemplate.Table, tasktemplate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ward.TaskTemplatesTable, ward.TaskTemplatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ward entity from the query.
// Returns a *NotFoundError when no Ward was found.
func (wq *WardQuery) First(ctx context.Context) (*Ward, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ward.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WardQuery) FirstX(ctx context.Context) *Ward {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ward ID from the query.
// Returns a *NotFoundError when no Ward ID was found.
func (wq *WardQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ward.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WardQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ward entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ward entity is found.
// Returns a *NotFoundError when no Ward entities are found.
func (wq *WardQuery) Only(ctx context.Context) (*Ward, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ward.Label}
	default:
		return nil, &NotSingularError{ward.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WardQuery) OnlyX(ctx context.Context) *Ward {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ward ID in the query.
// Returns a *NotSingularError when more than one Ward ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WardQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ward.Label}
	default:
		err = &NotSingularError{ward.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WardQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Wards.
func (wq *WardQuery) All(ctx context.Context) ([]*Ward, error) {
	ctx = setContextOp(ctx, wq.ctx, "All")
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ward, *WardQuery]()
	return withInterceptors[[]*Ward](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WardQuery) AllX(ctx context.Context) []*Ward {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ward IDs.
func (wq *WardQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, "IDs")
	if err = wq.Select(ward.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WardQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, "Count")
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WardQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WardQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, "Exist")
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WardQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WardQuery) Clone() *WardQuery {
	if wq == nil {
		return nil
	}
	return &WardQuery{
		config:            wq.config,
		ctx:               wq.ctx.Clone(),
		order:             append([]ward.OrderOption{}, wq.order...),
		inters:            append([]Interceptor{}, wq.inters...),
		predicates:        append([]predicate.Ward{}, wq.predicates...),
		withRooms:         wq.withRooms.Clone(),
		withTaskTemplates: wq.withTaskTemplates.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithRooms tells the query-builder to eager-load the nodes that are connected to
// the "rooms" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WardQuery) WithRooms(opts ...func(*RoomQuery)) *WardQuery {
	query := (&RoomClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withRooms = query
	return wq
}

// WithTaskTemplates tells the query-builder to eager-load the nodes that are connected to
// the "task_templates" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WardQuery) WithTaskTemplates(opts ...func(*TaskTemplateQuery)) *WardQuery {
	query := (&TaskTemplateClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withTaskTemplates = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ward.Query().
//		GroupBy(ward.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WardQuery) GroupBy(field string, fields ...string) *WardGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WardGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = ward.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Ward.Query().
//		Select(ward.FieldName).
//		Scan(ctx, &v)
func (wq *WardQuery) Select(fields ...string) *WardSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WardSelect{WardQuery: wq}
	sbuild.label = ward.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WardSelect configured with the given aggregations.
func (wq *WardQuery) Aggregate(fns ...AggregateFunc) *WardSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !ward.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ward, error) {
	var (
		nodes       = []*Ward{}
		_spec       = wq.querySpec()
		loadedTypes = [2]bool{
			wq.withRooms != nil,
			wq.withTaskTemplates != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ward).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ward{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withRooms; query != nil {
		if err := wq.loadRooms(ctx, query, nodes,
			func(n *Ward) { n.Edges.Rooms = []*Room{} },
			func(n *Ward, e *Room) { n.Edges.Rooms = append(n.Edges.Rooms, e) }); err != nil {
			return nil, err
		}
	}
	if query := wq.withTaskTemplates; query != nil {
		if err := wq.loadTaskTemplates(ctx, query, nodes,
			func(n *Ward) { n.Edges.TaskTemplates = []*TaskTemplate{} },
			func(n *Ward, e *TaskTemplate) { n.Edges.TaskTemplates = append(n.Edges.TaskTemplates, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WardQuery) loadRooms(ctx context.Context, query *RoomQuery, nodes []*Ward, init func(*Ward), assign func(*Ward, *Room)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Ward)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Room(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ward.RoomsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ward_rooms
		if fk == nil {
			return fmt.Errorf(`foreign-key "ward_rooms" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ward_rooms" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WardQuery) loadTaskTemplates(ctx context.Context, query *TaskTemplateQuery, nodes []*Ward, init func(*Ward), assign func(*Ward, *TaskTemplate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Ward)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TaskTemplate(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ward.TaskTemplatesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ward_task_templates
		if fk == nil {
			return fmt.Errorf(`foreign-key "ward_task_templates" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ward_task_templates" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wq *WardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ward.Table, ward.Columns, sqlgraph.NewFieldSpec(ward.FieldID, field.TypeUUID))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ward.FieldID)
		for i := range fields {
			if fields[i] != ward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(ward.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = ward.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WardGroupBy is the group-by builder for Ward entities.
type WardGroupBy struct {
	selector
	build *WardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WardGroupBy) Aggregate(fns ...AggregateFunc) *WardGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, "GroupBy")
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WardQuery, *WardGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WardGroupBy) sqlScan(ctx context.Context, root *WardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WardSelect is the builder for selecting fields of Ward entities.
type WardSelect struct {
	*WardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WardSelect) Aggregate(fns ...AggregateFunc) *WardSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, "Select")
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WardQuery, *WardSelect](ctx, ws.WardQuery, ws, ws.inters, v)
}

func (ws *WardSelect) sqlScan(ctx context.Context, root *WardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
