primary_region = "ams"

[build]
  # EventStoreDB LTS v23.10
  image = "eventstore/eventstore@sha256:87caf34536ef5410808b173114bc3657210b0307c0233dae80514127ff0861cc"

[env]
  EVENTSTORE_NODE_IP="::"
  EVENTSTORE_INSECURE=true
  EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  EVENTSTORE_RUN_PROJECTIONS="All"
  EVENTSTORE_TELEMETRY_OPTOUT=true

[mounts]
  source = "helpwave_staging_eventstoredb"
  destination = "/var/lib/eventstore"

[[vm]]
  memory = "768MB"
  cpu_kind = "shared"
  cpus = 1
