name: Buf

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  # renovate: datasource=golang-version depName=golang/go
  GO_VERSION: '1.21'
  # renovate: datasource=github-release depName=bufbuild/buf
  BUF_CLI_VERSION: '1.28.1'
  # renovate: datasource=github-releases depName=favadi/protoc-go-inject-tag
  PROTOC_GO_INJECT_TAG_VERSION: '1.4.0'

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: v${{ env.BUF_CLI_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
  generate-protos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: v${{ env.BUF_CLI_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go install github.com/favadi/protoc-go-inject-tag@v${{ env.PROTOC_GO_INJECT_TAG_VERSION }}
      - run: bash protos.sh
      - name: Break if generated go modules are not checked in
        # exits with 1 if there were differences, and 0 if there were none
        run: git diff --quiet gen
      - name: Upload docs
        if: success() && github.ref == 'refs/heads/main'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'hw-proto-docs'
          directory: 'proto_docs'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
# TODO (arm-versioning): Arm versioning by removing the comments of the following lines
#      - uses: bufbuild/buf-breaking-action@v1
#        with:
#          against: 'https://github.com/${{ github.repository }}.git#branch=main'
