name: Buf

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
  generate-protos:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/helpwave/dev-go:testing-1 # TODO
      volumes:
        - ${{ github.workspace }}:/github/workspace
    permissions:
      contents: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - run: bash protos.sh
      - name: Break if generated go modules are not checked in
        # exits with 1 if there were differences, and 0 if there were none
        run: git diff --quiet gen
      - name: Upload docs
        if: success() && github.ref == 'refs/heads/main'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'hw-proto-docs'
          directory: 'proto_docs'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
# TODO (arm-versioning): Arm versioning by removing the comments of the following lines
#      - uses: bufbuild/buf-breaking-action@v1
#        with:
#          against: 'https://github.com/${{ github.repository }}.git#branch=main'
