name: Buf

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
  generate-protos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make proto
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: gen
      - name: Break if files have changed
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: exit 1
      - name: Upload docs
        if: success() && github.ref == 'refs/heads/main'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'hw-proto-docs'
          directory: 'proto_docs'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
