name: 'Deploy to Fly'

on:
  workflow_call:
    inputs:
      service:
        description: 'The name of the service (name of the directory).'
        type: string
        required: true
      app:
        description: 'The name of the app on Fly.'
        type: string
        required: true
      organization:
        description: 'The name of the organization on Fly.'
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.app }}
  cancel-in-progress: true

jobs:

  fly-toml:
    runs-on: ubuntu-latest
    outputs:
      exist: ${{ steps.fly-toml.outputs.fly-toml-exist }}
    steps:
      - uses: actions/checkout@v4
      - name: Does a fly.toml exist?
        id: fly-toml
        run: |
          echo "fly-toml-exist=$(test -f services/$service/fly.toml && echo true)" >> $GITHUB_OUTPUT
        env:
          service: ${{ inputs.service }}

  deploy:
    runs-on: ubuntu-latest
    needs: fly-toml
    if: ${{ needs.fly-toml.outputs.exist == 'true' }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Configure Dapr for deployment
        run: sed -i "s/helpwave-staging/$organization/g" dapr/config.yaml
        env:
          organization: ${{ inputs.organization }}
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy --config services/${{ inputs.service }}/fly.toml --app ${{ inputs.app }} --remote-only
        env:
          DOCKER_BUILDKIT: 1
