name: 'Deploy to Fly'

on:
  workflow_call:
    inputs:
      service:
        description: 'The name of the service.'
        type: string
        required: true

env:
  APP_PREFIX: 'helpwave-staging-'

defaults:
  run:
    working-directory: services/${{ inputs.service }}

jobs:

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app ${{ env.APP_PREFIX }}${{ inputs.service }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
