name: hibernate-gke

on:
  workflow_dispatch:
    inputs:
      zone:
        description: 'The zone of the cluster'
        required: true
        default: 'europe-west3-b'
      cluster:
        description: 'The name of the cluster'
        required: true
        default: 'helpwave-test-gke-staging'
      nodePool:
        description: 'The name of the node-pool inside the cluster'
        required: true
        default: 'primary-spot-nodes'
      numNodes:
        description: 'The number of nodes for scaling the node-pool up after hibernation'
        required: false
        default: '3'
      desiredState:
        description: 'The desired state of the cluster. Checked for on. Unchecked for off.'
        required: true
        type: boolean

jobs:

  hibernate-gke:

    runs-on: ubuntu-latest
    steps:

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Turn cluster on or off
        run: |
          if [[ "$desiredState" == "true" ]]; then
            gcloud container clusters resize $cluster --quiet --zone $zone --node-pool $nodePool --num-nodes $numNodes
          else
            gcloud container clusters resize $cluster --quiet --zone $zone --node-pool $nodePool --num-nodes 0
          fi
        env:
          zone: ${{ inputs.zone }}
          cluster: ${{ inputs.cluster }}
          nodePool: ${{ inputs.nodePool }}
          numNodes: ${{ inputs.numNodes }}
          desiredState: ${{ inputs.desiredState }}
