name: spicedb

env:
  # renovate: datasource=github-releases depName=authzed/zed
  ZED_VERSION: '0.23.0'

on:
  pull_request:
    paths:
      - 'spicedb/*'
      - 'cmd/spice/*'
      - 'go.*'
      - '.github/workflows/spicedb.yaml'
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      - 'spicedb/*'
      - 'cmd/spice/*'
      - 'go.*'
      - '.github/workflows/spicedb.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Get zed
        run: |
          wget "https://github.com/authzed/zed/releases/download/v${ZED_VERSION}/zed_${ZED_VERSION}_linux_amd64.deb" -O zed.deb
          sudo apt install -y ./zed.deb
      - run: |
          go run cmd/spice/spice.go test

# TODO: pull staging data and smoke-test migration
