name: spicedb

env:
  # renovate: datasource=github-releases depName=authzed/zed
  ZED_VERSION: '0.20.0'

on:
  pull_request:
    paths:
      - 'spicedb/*'
      - 'spice.go'
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      - 'spicedb/*'
      - 'spice.go'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Get zed
        run: |
          wget https://github.com/authzed/zed/releases/download/v${ZED_VERSION}/zed_${ZED_VERSION}_linux_amd64.deb -O zed.deb
          apt install -y ./zed.deb
      - run: |
          go run spicedb.go test

# TODO: pull staging data and smoke-test migration
